Modifiers on new selection UI
krmeet/sound-space-plus-rewrite pull request #4
Opened 2023-10-22 04:09 UTC by anthony-63

The implementation is very crude BUT functional. If anything is not to your liking just give me a review

CHANGES:
- Modifiers UI
- Speed Modifier
- Nofail modifier
- Reset modifiers
- Seek slider
- Fix pages bug where when there are no search results, pages would be 0, then when results come back it will STAY on 0, which now it automatically goes to the first valid page

2023-10-22 04:28 UTC, AllusionistZ commented
Guys. This is awesome.

2023-10-22 10:34 UTC, krmeet requested changes
Please see comments.

2023-10-22 10:34 UTC, krmeet commented on scripts/menu/maplist/MapDetails.gd
> +@export var selected_mapset: Mapset = null
what is this for

2023-10-22 10:34 UTC, krmeet commented on scripts/menu/maplist/Modifiers.gd
> +	_ready()
this makes connect() run again

2023-10-22 10:34 UTC, krmeet commented on scenes/Init.tscn
> +[ext_resource type="Theme" uid="uid://tin0gsmmldph" path="res://themes/modifier_theme.tres" id="1_mls4r"]
why is the theme changed in this scene?

2023-10-22 10:34 UTC, krmeet commented on scripts/menu/maplist/MapDetails.gd
> +	$Sections/Extra/Modifiers.update_time_label()
this should be done in the modifiers script

2023-10-22 10:34 UTC, krmeet commented on scenes/Menu.tscn
> +[ext_resource type="Theme" uid="uid://tin0gsmmldph" path="res://themes/modifier_theme.tres" id="1_j808x"]
same with the init scene? this should not be replacing the main theme

2023-10-22 20:26 UTC, anthony-63 commented
Done, review the commits

2023-10-22 20:48 UTC, krmeet commented on scenes/Init.tscn
> +theme = ExtResource("2_p8tgo")
This is not the root of the scene what

2023-10-22 20:53 UTC, krmeet commented on scripts/menu/maplist/Modifiers.gd
this still calls _ready() again please dont do this

2023-10-22 20:55 UTC, anthony-63 commented on scripts/menu/maplist/Modifiers.gd
where??? you can check the commit for it, i literally removed the call for _ready()

2023-10-22 20:56 UTC, krmeet requested changes
see comments again, some things are ok others are ???

2023-10-22 21:09 UTC, krmeet approved these changes
good enough but i might need to make some code guidelines in the future :3

2023-10-23 06:50 UTC, David20122 approved these changes

2023-10-23 13:06 UTC, merged